#!/system/bin/sh
# Brainmaster Tweaks

# Flags every mounted partition as non rotational
MTD=`ls -d /sys/block/mtd*`;
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;

for j in $DM $MTD $LOOP $RAM;
do
echo "0" > $j/queue/rotational;
done

# Remounting the file systems with noatime and nodiratime flags to save battery and CPU cycles
mount -o remount,noauto_da_alloc,nosuid,nodev,noatime,nodiratime /data /data

# Define the memory thresholds at which the above process classes will
# be killed.  These numbers are in pages (4k).
setprop ro.FOREGROUND_APP_MEM 1536
setprop ro.VISIBLE_APP_MEM 2048
setprop ro.PERCEPTIBLE_APP_MEM 4096
setprop ro.HEAVY_WEIGHT_APP_MEM 4096
setprop ro.SECONDARY_SERVER_MEM 15360
setprop ro.BACKUP_APP_MEM 15360
setprop ro.HOME_APP_MEM 15360
setprop ro.HIDDEN_APP_MEM 17920
setprop ro.EMPTY_APP_MEM 20480

# Tweak memory
echo "0,1,2,4,7,15" > /sys/module/lowmemorykiller/parameters/adj;
echo "1" > /proc/sys/vm/overcommit_memory;
echo "4" > /proc/sys/vm/min_free_order_shift;

# Set init its forked children's oom_adj.
echo "-16" > /proc/1/oom_adj;

# Tweak lowmemkiller
echo "1536,2048,4096,15360,17920,20480" > /sys/module/lowmemorykiller/parameters/minfree; 

# Tweak background echoout
echo "500" > /proc/sys/vm/dirty_writeback_centisecs;
echo "50" > /proc/sys/vm/dirty_expire_centisecs;
echo "4" > /proc/sys/vm/dirty_ratio;
echo "2" > /proc/sys/vm/dirty_background_ratio;

# Tweak TCP
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "404480" > /proc/sys/net/core/wmem_max;
echo "404480" > /proc/sys/net/core/rmem_max;
echo "256960" > /proc/sys/net/core/rmem_default;
echo "256960" > /proc/sys/net/core/wmem_default;
echo "4096 16384 404480" > /proc/sys/net/ipv4/tcp_wmem;
echo "4096 87380 404480" > /proc/sys/net/ipv4/tcp_rmem;
setprop net.tcp.buffersize.default 4096,87380,404480,4096,16384,404480;
setprop net.tcp.buffersize.wifi 4096,87380,404480,4096,16384,404480;
setprop net.tcp.buffersize.umts 4096,87380,404480,4096,16384,404480;
    
# Tweak sdcard read ahead cache size
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

# SQLite Database optimization
for i in \
`find /data -iname "*.db"`
do \
sqlite3 $i 'VACUUM;'; 
done
